services:
  web:
    build: .
    expose:
      - "5545"
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: false
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///cafeteria.db
